[package]
name = "pluviolithic/avatar-editor-rewrite"
version = "1.0.0"
authors = ["Eric McKanna <e-mckanna@onu.edu>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"

[dependencies]
Janitor = "howmanysmall/janitor@1.13.14"
slidermodule = "aerodymier/slidermodule@0.2.4"

[server-dependencies]
ProfileService = "grilme99/profileservice@1.0.0"
